### ISSUE TITLE
Typo in prerequisite specification (File::Stat instead File::stat)

### ISSUE THREAD

**Issue by eserte** [jonasbn/mbb#2]
See subject. Additionally, t/runtests.t fails because of the same problem:

```
Can't locate File/Stat.pm in @INC (you may need to install the File::Stat module) (@INC contains: /tmpfs/.cpan-build/2015090209/Module-Build-Bundle-0.15-kAcbrw/t/../t /tmpfs/.cpan-build/2015090209/Module-Build-Bundle-0.15-kAcbrw/blib/lib /tmpfs/.cpan-build/2015090209/Module-Build-Bundle-0.15-kAcbrw/blib/arch /opt/perl-5.20.3-RC2/lib/site_perl/5.20.3/x86_64-linux /opt/perl-5.20.3-RC2/lib/site_perl/5.20.3 /opt/perl-5.20.3-RC2/lib/5.20.3/x86_64-linux /opt/perl-5.20.3-RC2/lib/5.20.3 .) at /tmpfs/.cpan-build/2015090209/Module-Build-Bundle-0.15-kAcbrw/t/../t/Test/Class/Module/Build/Bundle/Contents.pm line 11.
BEGIN failed--compilation aborted at /tmpfs/.cpan-build/2015090209/Module-Build-Bundle-0.15-kAcbrw/t/../t/Test/Class/Module/Build/Bundle/Contents.pm line 11.
Compilation failed in require at t/runtests.t line 12.
BEGIN failed--compilation aborted at t/runtests.t line 12.
t/runtests.t .............. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by jonasbn** [comment]
Hmmm, I could change the use, but I am actually using [File::Stat](https://metacpan.org/pod/File::Stat) over [File::stat](https://metacpan.org/pod/File::stat), simply because I liked the interface better.

Ref: https://metacpan.org/search?q=File%3A%3AStat

The central problem with File::Stat is actually installation, an example run on my local machine

```
> cpanm File::Stat
! Finding File::Stat on cpanmetadb failed.
File::Stat is up to date. (0.01)
```

See also: https://rt.cpan.org/Ticket/Display.html?id=83208

**Comment by jonasbn** [comment]
The interface looked fairly similar, so I attempted a removal of File::Stat from my local installation and applied the change you proposed - and YAY! the test suite still passes.

I will apply the change you propose and make a release

**Comment by jonasbn** [comment]
I categorized this as a bug since File::Stat is causing so much trouble, I remembered had been bitten by this before, so I checked [my notes](https://logiclab.jira.com/wiki/display/OPEN/File-Stat) and yes, I recommend avoiding File::Stat.

**Comment by jonasbn** [comment]
Closing, uploaded release 0.16 to CPAN
